# Vendored from spine/generated/python/protocol.py — re-sync via spine/scripts/sync-mbrl.sh
# GENERATED by spine-codegen — DO NOT EDIT.
# Source of truth: spine/src/Spine/Wire.hs + Spine/Schema.hs

VERSION = 1

VERBS = {
    "hello": {"status": "served", "dir": "->", "desc": "handshake; reply {version}"},
    "pull.runs": {"status": "served", "dir": "<->", "desc": "run list: name, group, last_step, n_points, keys"},
    "pull.metric": {"status": "served", "dir": "<->", "desc": "full curve {steps, values} (sqlite-preferred)"},
    "pull.metric_since": {"status": "served", "dir": "<->", "desc": "incremental curve, env_steps > since"},
    "pull.datasets": {"status": "served", "dir": "<->", "desc": "checkpoint / dataset catalog"},
    "pull.surface": {"status": "served", "dir": "<->", "desc": "reward-surface slice {z, curv, budget, path, ...}"},
    "submit.spec": {"status": "served", "dir": "->", "desc": "author + launch one run"},
    "submit.sweep": {"status": "served", "dir": "->", "desc": "expand axes x seeds -> launch each arm"},
    "pull.run_status": {"status": "served", "dir": "<->", "desc": "one run's launch state (running/finished/failed)"},
    "pull.launched": {"status": "served", "dir": "<->", "desc": "all launched runs + their states"},
    "pull.log": {"status": "served", "dir": "<->", "desc": "incremental run-log lines (live-tail)"},
    "run.cancel": {"status": "served", "dir": "->", "desc": "terminate a running launched child"},
    "search.submit": {"status": "served", "dir": "<->", "desc": "W9 random search: sample arms (typed distributions), persist state, launch the first batch"},
    "search.status": {"status": "served", "dir": "<->", "desc": "a search's arm table (+ last metric per arm) or the catalog (no name)"},
    "search.tick": {"status": "served", "dir": "<->", "desc": "advance a search: sync states, median-rule stop losers (run.cancel), launch queued"},
    "env.reset": {"status": "godot", "dir": "->", "desc": "train seam — served by Godot serve_env"},
    "env.step": {"status": "godot", "dir": "->", "desc": "train seam — served by Godot serve_env"},
    "env.spec": {"status": "godot", "dir": "->", "desc": "train seam — served by Godot serve_env"},
    "infer.load": {"status": "godot", "dir": "->", "desc": "in-engine ONNX — not served by the runner"},
    "infer.run": {"status": "godot", "dir": "->", "desc": "in-engine ONNX — not served by the runner"},
    "pull.artifacts": {"status": "served", "dir": "<->", "desc": "a run's artifact manifest (checkpoints + W&B artifacts) + its resolved config"},
    "pull.sweep": {"status": "served", "dir": "<->", "desc": "sweep cells grid: catalog (no name) or flattened arm-rows from results/<name>_cells.jsonl"},
    "pull.diagnostics": {"status": "served", "dir": "<->", "desc": "PCA/cross-validation reports: catalog (no name) or the named results/diagnostics/<name>.json payload"},
    "pull.operator_spectrum": {"status": "served", "dir": "<->", "desc": "operator singular-value spectrum over training: {steps, modes[][], mode_keys} assembled from the op/sv* curves"},
    "pull.tensor": {"status": "served", "dir": "<->", "desc": "named tensor snapshot: catalog (no name) or {run,name,step,matrix[][]/vector[],eig?} for a named tensor (gram, op_d, op_p, ...) under results/<run>/tensors/"},
    "pull.salience": {"status": "served", "dir": "<->", "desc": "input/feature salience map: |d reward / d obs| over a batch, {run,step,salience[],dims} (latest or by step)"},
    "error": {"status": "served", "dir": "<-", "desc": "error envelope {code, message}"},
}

SERVED = {"hello", "pull.runs", "pull.metric", "pull.metric_since", "pull.datasets", "pull.surface", "submit.spec", "submit.sweep", "pull.run_status", "pull.launched", "pull.log", "run.cancel", "search.submit", "search.status", "search.tick", "pull.artifacts", "pull.sweep", "pull.diagnostics", "pull.operator_spectrum", "pull.tensor", "pull.salience", "error"}
GODOT = {"env.reset", "env.step", "env.spec", "infer.load", "infer.run"}

METRIC_KEYS = ["eval/return", "loss/total", "loss/dyn", "loss/reward", "loss/value", "loss/policy", "penalty/value", "penalty/lambda", "policy/entropy", "policy/ret_scale", "imagine/return_mean", "imagine/return_var", "imagine/horizon", "model/reward_disagreement", "dyn/disagreement", "dyn/calib_corr", "vae/recon", "vae/kl"]

AXIS_PATHS = ["penalty.schedule.lam0", "penalty.schedule.floor", "penalty.n_probes", "model.latent_dim", "model.hidden", "model.depth", "model.latent_cap_mult", "imagination.horizon", "imagination.pessimism", "optim.model_lr", "optim.policy_lr", "optim.batch_size", "algo.dynamics_ensemble", "algo.ensemble_pessimism", "spectral.n_features", "spectral.heads"]
