# Vendored from spine/generated/python/validate.py — re-sync via spine/scripts/sync-mbrl.sh
# GENERATED by spine-codegen — DO NOT EDIT.
# Source of truth: spine/src/Spine/Wire.hs + Spine/Schema.hs
# Spectral house-rule validator — compiled from Spine/Validate/Rules.hs.

def _dig(spec, path):
    cur = spec
    parts = path.split(".")
    for k in parts[:-1]:
        cur = cur.get(k, {}) if isinstance(cur, dict) else {}
    return (cur if isinstance(cur, dict) else {}), parts[-1]

def _to_float(v, default=0.0):
    if isinstance(v, bool):
        return default
    try:
        return float(v)
    except (TypeError, ValueError):
        return default

def _to_int(v, default=0):
    if isinstance(v, bool):
        return default
    try:
        return int(float(v))
    except (TypeError, ValueError):
        return default

def _gstr(spec, path, default):
    par, k = _dig(spec, path)
    return str(par.get(k, default))

def _graw(spec, path):
    par, k = _dig(spec, path)
    return str(par.get(k)) if k in par else "None"

def _gfloat(spec, path, getdef):
    par, k = _dig(spec, path)
    return _to_float(par.get(k, getdef), getdef)

def _gint(spec, path, getdef, coercedef):
    par, k = _dig(spec, path)
    return _to_int(par.get(k, getdef), coercedef)

def _gbool(spec, path, default):
    par, k = _dig(spec, path)
    return bool(par.get(k, default))

def _gempty(spec, path):
    par, k = _dig(spec, path)
    v = par.get(k)
    return v is None or (isinstance(v, list) and len(v) == 0)

def validate(spec):
    warns = []
    if _gstr(spec, "algo.critic", "value") != "value":
        warns.append("algo.critic '" + _graw(spec, "algo.critic") + "' is implemented + tested but not yet consumed by the Trainer — the run trains with the default value head")
    if _gstr(spec, "algo.actor", "gaussian") != "gaussian":
        warns.append("algo.actor '" + _graw(spec, "algo.actor") + "' is implemented + tested but not yet consumed by the Trainer — the run trains with the default Gaussian policy")
    if _gstr(spec, "algo.planner", "none") != "none":
        warns.append("algo.planner '" + _graw(spec, "algo.planner") + "' is implemented + tested but not yet consumed by the Trainer — actions come from the policy, not MPC")
    if (_gstr(spec, "model.encoder", "") == "custom") and (_gempty(spec, "model.encoder_net")):
        warns.append("model.encoder=custom but encoder_net is empty — wire an NN-layer chain into the encoder's net pin")
    if (_gbool(spec, "spectral.enabled", False)) and ((_gstr(spec, "penalty.schedule.kind", "") in ("step", "sincos", "sin2chirp",)) or (_gfloat(spec, "penalty.schedule.floor", 0.0) <= 0.0)):
        warns.append("spectral path: schedule '" + _gstr(spec, "penalty.schedule.kind", "") + "' (floor " + str(_gfloat(spec, "penalty.schedule.floor", 0.0)) + ") is zero-touching — use cuberoot with floor > 0 (ledger 2026-06-07)")
    if (_gbool(spec, "spectral.enabled", False)) and (_gint(spec, "model.latent_cap_mult", 4, 0) > 1):
        warns.append("spectral path: latent_cap_mult " + str(_gint(spec, "model.latent_cap_mult", 4, 0)) + " > 1 over-resolves the closed-form fit — set 1 (ledger 2026-06-07)")
    return warns
